use crate::radcomp::extension::types as wit;

// Target/TimeoutPolicy WIT conversions generated by shared macros in
// `rad_models::rpc_conversion` (see that module's docs); both directions
// are needed here since `conv/rpc.rs` converts `RasRpcCommand` both ways.
rad_models::impl_rpc_target_wit_to_core!(wit);
rad_models::impl_rpc_target_core_to_wit!(wit);
rad_models::impl_rpc_timeout_policy_wit_to_core!(wit);
rad_models::impl_rpc_timeout_policy_core_to_wit!(wit);

impl From<wit::PendingToolCallInfo> for rad_models::PendingToolCallInfo {
    fn from(info: wit::PendingToolCallInfo) -> Self {
        rad_models::PendingToolCallInfo {
            id: info.id,
            name: info.name,
            arguments: info.arguments,
            pgid: info.pgid.map(|n| n.to_string()),
        }
    }
}

impl From<rad_models::PendingToolCallInfo> for wit::PendingToolCallInfo {
    fn from(info: rad_models::PendingToolCallInfo) -> Self {
        wit::PendingToolCallInfo {
            id: info.id,
            name: info.name,
            arguments: info.arguments,
            pgid: info.pgid.and_then(|s| s.parse().ok()),
        }
    }
}

pub mod event;
pub mod rpc;
