#![deny(clippy::pedantic)]

#[allow(
    unsafe_op_in_unsafe_fn,
    clippy::same_length_and_capacity,
    clippy::pedantic
)]
mod bindings {
    wit_bindgen::generate!({
        path: "../../wit/rad.wit",
        world: "rad-security-guard",
    });

    use super::SecurityGuardImpl;
    export!(SecurityGuardImpl);
}

pub use bindings::*;

use self::radcomp::extension::types as wit;
use rad_models::RasRpcCommand as CoreRpcCommand;

mod policy;

struct SecurityGuardImpl;

impl Guest for SecurityGuardImpl {
    fn verify_rpc(command: wit::RasRpcCommand) -> bool {
        let rpc_cmd = CoreRpcCommand::from(command);
        policy::evaluate(&rpc_cmd)
    }
}

/// Asks the host for this extension's own `config` blob (`ExtensionConfig
/// .config` in `~/.rad/config.json`), the mechanism `policy` uses to load
/// its blocklist patterns instead of the hardcoded literals this crate used
/// to carry.
pub(crate) fn call_host(command: CoreRpcCommand) -> Result<serde_json::Value, String> {
    let wit_cmd = wit::RasRpcCommand::from(command);
    match host_rpc(&wit_cmd) {
        Ok(json_str) => {
            if json_str.is_empty() || json_str == "null" {
                Ok(serde_json::Value::Null)
            } else {
                serde_json::from_str(&json_str).map_err(|e| format!("JSON parse error from host: {e}"))
            }
        }
        Err(err_msg) => Err(err_msg),
    }
}

// Conversions generated by shared macros in `rad_models::rpc_conversion`
// instead of hand-duplicating the same match this crate used to carry —
// see that module's docs. Both directions are needed now: `verify_rpc`
// inspects incoming commands (wit-to-core), and `policy` constructs a
// `GetExtensionConfig` command to send to the host (core-to-wit).
rad_models::impl_rpc_target_wit_to_core!(wit);
rad_models::impl_rpc_target_core_to_wit!(wit);
rad_models::impl_rpc_timeout_policy_wit_to_core!(wit);
rad_models::impl_rpc_timeout_policy_core_to_wit!(wit);
rad_models::impl_rpc_command_wit_to_core!(wit);

impl From<CoreRpcCommand> for wit::RasRpcCommand {
    fn from(cmd: CoreRpcCommand) -> Self {
        if let Some(w) = rad_models::common_rpc_command_core_to_wit!(wit, cmd.clone()) {
            return w;
        }
        match cmd {
            CoreRpcCommand::OpenFile { .. } | CoreRpcCommand::OpenProcess { .. } => {
                panic!("OpenFile and OpenProcess are now directly imported capabilities")
            }
            _ => unreachable!(),
        }
    }
}
