// `RasRpcCommand` <-> WIT conversions. Both directions generated by shared
// macros in `rad_models::rpc_conversion` instead of hand-duplicating the
// same ~25-arm match this crate used to carry across bucketed helper
// functions — see that module's docs. `OpenFile`/`OpenProcess` have no WIT
// equivalent; this crate never constructs them itself, so the core-to-wit
// residual just panics if one ever reaches here.
use crate::radcomp::extension::types as wit;
use rad_models::RasRpcCommand as CoreRpcCommand;

rad_models::impl_rpc_command_wit_to_core!(wit);

impl From<CoreRpcCommand> for wit::RasRpcCommand {
    fn from(cmd: CoreRpcCommand) -> Self {
        if let Some(w) = rad_models::common_rpc_command_core_to_wit!(wit, cmd.clone()) {
            return w;
        }
        match cmd {
            CoreRpcCommand::OpenFile { .. } | CoreRpcCommand::OpenProcess { .. } => {
                panic!("OpenFile and OpenProcess are now directly imported capabilities")
            }
            _ => unreachable!(),
        }
    }
}
