// `RasRpcCommand` <-> WIT conversions, split out of `bindings.rs` to stay
// under the 300-line file limit. The bulk of the match is generated by
// shared macros in `rad_models::rpc_conversion` (see that module's docs)
// so this file doesn't hand-duplicate the same ~25-arm match every other
// extension crate also needs. `OpenFile`/`OpenProcess` have no WIT
// equivalent (see macro docs) — the host is the one place that must
// convert them for real, since it's the one deciding whether an `OpenFile`
// becomes a `FileRead` or `FileWrite` based on `writeable`.
use super::wit;
use rad_models::RasRpcCommand as CoreRasRpcCommand;

rad_models::impl_rpc_target_wit_to_core!(wit);
rad_models::impl_rpc_target_core_to_wit!(wit);
rad_models::impl_rpc_timeout_policy_wit_to_core!(wit);
rad_models::impl_rpc_timeout_policy_core_to_wit!(wit);
rad_models::impl_rpc_command_wit_to_core!(wit);

impl From<CoreRasRpcCommand> for wit::RasRpcCommand {
    fn from(cmd: CoreRasRpcCommand) -> Self {
        if let Some(w) = rad_models::common_rpc_command_core_to_wit!(wit, cmd.clone()) {
            return w;
        }
        match cmd {
            CoreRasRpcCommand::OpenFile { path, writeable } => {
                if writeable {
                    wit::RasRpcCommand::FileWrite(wit::FileWritePayload {
                        path: path.to_string_lossy().into_owned(),
                        data: vec![],
                    })
                } else {
                    wit::RasRpcCommand::FileRead(path.to_string_lossy().into_owned())
                }
            }
            CoreRasRpcCommand::OpenProcess { command } => {
                wit::RasRpcCommand::SpawnBashProcess(command)
            }
            _ => unreachable!(),
        }
    }
}
