use crate::radcomp::extension::types as wit;
use rad_models::RasRpcCommand as CoreRpcCommand;

// Conversions generated by shared macros in `rad_models::rpc_conversion`
// instead of hand-duplicating the same match this crate used to carry —
// see that module's docs. This crate constructs commands to send to the
// host (never inspects incoming ones), so only core-to-wit is needed —
// which `common_rpc_command_core_to_wit!` itself depends on for
// `SetStreamTimeoutPolicy`'s nested `Target`/`TimeoutPolicy` fields.
rad_models::impl_rpc_target_core_to_wit!(wit);
rad_models::impl_rpc_timeout_policy_core_to_wit!(wit);

impl From<CoreRpcCommand> for wit::RasRpcCommand {
    fn from(cmd: CoreRpcCommand) -> Self {
        if let Some(w) = rad_models::common_rpc_command_core_to_wit!(wit, cmd.clone()) {
            return w;
        }
        match cmd {
            CoreRpcCommand::OpenFile { .. } | CoreRpcCommand::OpenProcess { .. } => {
                panic!("OpenFile and OpenProcess are now directly imported capabilities")
            }
            _ => unreachable!(),
        }
    }
}
