//! Exercises the generated routing from outside, the way a module author's
//! crate sees it. Uses `routes!` rather than `module!` because the latter also
//! generates wasm component bindings, which cannot link in a native test — the
//! split exists so this logic stays testable without a wasm host.
use rad_sdk::{Error, Manifest};

#[derive(serde::Deserialize)]
struct GreetReq {
    who: String,
}

#[derive(serde::Serialize)]
struct GreetRes {
    text: String,
}

fn greet(req: GreetReq) -> Result<GreetRes, Error> {
    if req.who.is_empty() {
        return Err(Error::invalid("who must not be empty"));
    }
    Ok(GreetRes {
        text: format!("hello {}", req.who),
    })
}

#[derive(serde::Deserialize)]
struct NoopReq {}

#[derive(serde::Serialize)]
struct NoopRes {
    ok: bool,
}

fn noop(_req: NoopReq) -> Result<NoopRes, Error> {
    Ok(NoopRes { ok: true })
}

rad_sdk::routes! {
    name: "demo",
    version: "0.1.0",
    methods: {
        "demo.greet" => greet,
        "demo.noop"  => noop,
    }
}

#[test]
fn manifest_derives_provides_from_the_method_map() {
    // The point of deriving rather than declaring: these cannot drift apart.
    let m = Manifest::parse(&__RadModule::manifest()).unwrap();
    assert_eq!(m.name, "demo");
    assert_eq!(m.version, "0.1.0");
    assert_eq!(m.provides, vec!["demo.greet", "demo.noop"]);
}

#[test]
fn manifest_is_valid_against_rad_abi() {
    // Generated by the SDK, validated by the kernel's parser — the whole
    // reason `rad-abi` is shared.
    assert!(Manifest::parse(&__RadModule::manifest()).is_ok());
}

#[test]
fn handle_routes_and_serializes_both_directions() {
    let out = __RadModule::handle("demo.greet".into(), r#"{"who":"rad"}"#.into()).unwrap();
    assert_eq!(out, r#"{"text":"hello rad"}"#);
}

#[test]
fn unknown_methods_are_reported_not_trapped() {
    // §3.5: call-time validation degrades gracefully where link-time checking
    // is all-or-nothing.
    let err = __RadModule::handle("demo.nope".into(), "{}".into()).unwrap_err();
    assert!(
        err.contains("demo.nope"),
        "message should name the method: {err}"
    );
    assert!(
        err.contains("demo"),
        "message should name the module: {err}"
    );
}

#[test]
fn a_malformed_payload_names_the_problem() {
    let err = __RadModule::handle("demo.greet".into(), r#"{"wrong":1}"#.into()).unwrap_err();
    assert!(
        err.contains("did not match the expected shape"),
        "unhelpful message: {err}"
    );
}

#[test]
fn handler_errors_carry_their_kind_across() {
    let err = __RadModule::handle("demo.greet".into(), r#"{"who":""}"#.into()).unwrap_err();
    assert_eq!(err, "Invalid: who must not be empty");
}
