pub mod config;
pub mod fs;
pub mod process;
pub mod dag;
pub mod ipc;
pub mod wasm;
pub mod http;
pub mod session;
pub mod command;
pub mod orchestrator;
pub mod subsystems;
pub static THINKING_ACTIVE: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);
